!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - clip_range
    - linear_0.15
  - - ent_coef
    - 0.002
  - - gae_lambda
    - 0.97
  - - gamma
    - 0.995
  - - learning_rate
    - linear_0.0001
  - - max_grad_norm
    - 0.8
  - - n_envs
    - 4
  - - n_epochs
    - 10
  - - n_steps
    - 512
  - - n_timesteps
    - 1000000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-2, ortho_init=False, activation_fn=nn.ELU, net_arch=dict(pi=[256,
      256], vf=[256, 256]) )
  - - vf_coef
    - 0.5
